version: '3.5'
services:
  jenkins_server:
    image: jenkins/jenkins:2.393
    container_name: jenkins_server
    restart: always
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
    name: jenkins_data
    
